# Generated by Django 6.0.3 on 2026-05-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servises',
            options={},
        ),
        migrations.RemoveField(
            model_name='servises',
            name='user',
        ),
        migrations.AlterField(
            model_name='servises',
            name='img',
            field=models.ImageField(upload_to='services/'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('order_date', models.DateField(verbose_name='Дата візиту')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servises.servises', verbose_name='Послуга')),
            ],
        ),
    ]
