# Generated by Django 6.0.3 on 2026-05-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0002_alter_servises_options_remove_servises_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(verbose_name='Дата візиту'),
        ),
    ]
