# Generated by Django 6.0.3 on 2026-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0004_remove_order_created_at_remove_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='descrp',
            field=models.CharField(default='я працівник', max_length=400, verbose_name='ваш опис'),
        ),
    ]
