# Generated by Django 6.0.3 on 2026-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='servises/', verbose_name='фото співробітника'),
        ),
    ]
