# Generated by Django 6.0.3 on 2026-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0007_employee_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='ціна'),
        ),
    ]
