# Generated by Django 6.0.3 on 2026-06-15 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Find_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я тваринки")),
                ('type_pets', models.CharField(max_length=100, verbose_name='Тип тваринки')),
                ('age', models.PositiveIntegerField(verbose_name='вік')),
                ('img', models.ImageField(blank=True, null=True, upload_to='find_home/', verbose_name='Фото улюбленця')),
                ('discp', models.CharField(max_length=300, verbose_name='Опис тваринки')),
                ('contact', models.CharField(max_length=50, verbose_name='Контакт куди телефонувати')),
            ],
            options={
                'verbose_name': 'Шукають домівку',
            },
        ),
        migrations.CreateModel(
            name='Type_OF_PETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='тип тварини')),
            ],
            options={
                'verbose_name': 'Тип тварини',
            },
        ),
        migrations.CreateModel(
            name='find_Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=80, verbose_name='кличка')),
                ('pet_type', models.CharField(max_length=100, verbose_name='Вид тварини')),
                ('last_location', models.CharField(max_length=200, verbose_name='Останнє місцезнаходження')),
                ('discrp', models.CharField(max_length=300, verbose_name='Опис')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакти')),
                ('img', models.ImageField(blank=True, null=True, upload_to='lost_pets/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lost', 'Розшукується'), ('found', 'Знайдено')], default='lost', max_length=20, verbose_name='статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Зниклі тварини',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poroda', models.CharField(default='золотий ретривер', max_length=30, verbose_name='Порода')),
                ('name', models.CharField(max_length=40, verbose_name="ім'я")),
                ('age', models.PositiveIntegerField(verbose_name='вік')),
                ('weight', models.FloatField(verbose_name='вага')),
                ('passport_number', models.PositiveIntegerField(verbose_name='номер паспорта')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pets_photos/', verbose_name='Фото улюбленця')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type_of_pets', verbose_name='тип тварини')),
            ],
            options={
                'verbose_name': 'Тварини',
            },
        ),
    ]
