# Generated by Django 6.0.3 on 2026-05-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_OF_PETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='тип тварини')),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name="ім'я")),
                ('age', models.PositiveIntegerField(verbose_name='вік')),
                ('weight', models.PositiveIntegerField(verbose_name='вага')),
                ('passport_number', models.PositiveIntegerField(verbose_name='номер паспорта')),
                ('type_pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type_of_pets', verbose_name='тип тварини')),
            ],
            options={
                'verbose_name': 'Тварини',
            },
        ),
    ]
