# Generated by Django 6.0.3 on 2026-05-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type_of_pets',
            options={'verbose_name': 'Тип тварини'},
        ),
    ]
