# Generated by Django 6.0.3 on 2026-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_type_of_pets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='poroda',
            field=models.CharField(default='золотий ретривер', max_length=30, verbose_name='Порода'),
        ),
    ]
