# Generated by Django 6.0.3 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pets_poroda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pets_photos/', verbose_name='Фото улюбленця'),
        ),
    ]
